stages:
  - build
  - lint
  - test
  - deploy

variables:
  DOCKER_IMAGE: "tmdb-devops-challenge:latest"

build:
  stage: build
  tags:
    - shell
  script:
    - docker build -t $DOCKER_IMAGE .

lint:
  stage: lint
  dependencies:
    - build
  tags:
    - shell
  script:
    - docker run --rm $DOCKER_IMAGE npm run lint

test:
  stage: test
  dependencies:
    - build
  tags:
    - shell
  script:
    - if [ -n "$(docker run --rm $DOCKER_IMAGE find ./src -type f -name '*.test.*')" ]; then
        docker run --rm $DOCKER_IMAGE npm test;
      else
        echo "No tests found. Skipping test stage.";
      fi

deploy:
  stage: deploy
  dependencies:
    - build
  tags:
    - shell
  script:
    - docker stop tmdb-devops-challenge || true
    - docker rm tmdb-devops-challenge || true
    - docker run -d --name tmdb-devops-challenge -p 3000:3000 $DOCKER_IMAGE
  only:
    - main